-- Step 1: Add new enum values first
ALTER TYPE "VoyageStatus" ADD VALUE IF NOT EXISTS 'NEW';
ALTER TYPE "VoyageStatus" ADD VALUE IF NOT EXISTS 'OFFERED';
ALTER TYPE "VoyageStatus" ADD VALUE IF NOT EXISTS 'LOST';
ALTER TYPE "VoyageStatus" ADD VALUE IF NOT EXISTS 'EXPIRED';
ALTER TYPE "VoyageStatus" ADD VALUE IF NOT EXISTS 'WITHDRAWN';
